algoritmo "Exercício repita até número"
// Função :
// Autor : Carla Marcondes
// Data : 23/01/2024
// Seção de Declarações 
var

   numero : inteiro

inicio

      maior <- 0
      repita
      
            escreval ("Digite um número: ")
            leia (numero)
      
      ate numero = 0
      
            escreval
            escreval
            escreval ("Parabéns, você encontrou o número procurado! ")


fimalgoritmo
