algoritmo "Exercício Repira Até números pares"
// Função :
// Autor :  Carla Marcondes
// Data : 23/01/2024
// Seção de Declarações 
var

   numeropar, quantidade : inteiro

inicio

      numeropar <- 2
      quantidade <- 1

      repita
      
            escreval (numeropar)
            numeropar <- numeropar + 2
            quantidade <- quantidade + 1
      
      ate quantidade > 50
      
fimalgoritmo
