algoritmo "Vetor"
// Função :
// Autor : Carla Marcondes
// Data : 24/01/2024
// Seção de Declarações 
var

   letradigitada: vetor [1..10] de caracter
   indice: inteiro

inicio

      para indice de 1 ate 10 faca
      
           escreval ("Digite uma letra: ")
           leia (letradigitada [indice])

      fimpara
      
      escreval
      escreval ("A letra da posição 3 é ", letradigitada [3])

fimalgoritmo
