algoritmo "Olá, Mundo!"
// Função :
// Autor :
// Data : 03/01/2024
// Seção de Declarações 
var

inicio

      // Escreval com l no final faz a quebra do texto para a linha debaixo
      Escreval("Olá, Mundo!")
      Escreval ("Sou aluna de programação 101, Carla Marcondes")
      Escreval
      Escreval
      Escreva ("Olá, Mundo! pt2")
      Escreva ("Sou aluna aprendendo programação. pt 2")


fimalgoritmo
