algoritmo "Função SE e OU"
// Função :
// Autor : Carla Marcondes
// Data : 12/01/2024
// Seção de Declarações 
var

   cor: caracter

inicio

      Escreval ("Digite uma cor: ")
      leia (cor)
      
      Se ( cor = "azul" ) Ou ( cor = "amarelo") Entao

         Escreval ("A cor digitada é azul ou amarelo")
      
      Senao
      
           Escreval ("cor inválida!!!")
      
      FimSe

fimalgoritmo
