algoritmo "Função SE e E"
// Função :
// Autor : Carla Marcondes
// Data : 12/01/2024
// Seção de Declarações 
var

   numero : inteiro

inicio

      Escreval ("Digite um número entre 2 e 10: ")
      leia (numero)
      
      Se ( numero >= 2 ) e ( numero <= 10 ) Entao
         Escreval ("O ", numero,  " está dentro do intervalo de 2 a 10")
      
      Senao
      
           Escreval ("O número digitado não se encontra dentro do intervalo proposto")
      
      FimSe


fimalgoritmo
